// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4HP3c7WqG2ylDQQlrekDvfMQCLuTnUjc',
    appId: '1:726043694023:web:6faa1e30abdab0409ebfe2',
    messagingSenderId: '726043694023',
    projectId: 'shope-9bd78',
    authDomain: 'shope-9bd78.firebaseapp.com',
    storageBucket: 'shope-9bd78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtElapfkfdo8UB0gMENqOs3U_v-iaVi8',
    appId: '1:726043694023:android:91a472158630dc799ebfe2',
    messagingSenderId: '726043694023',
    projectId: 'shope-9bd78',
    storageBucket: 'shope-9bd78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZh7nzymgpZAjs42wzAlxJjQt38ir09TM',
    appId: '1:726043694023:ios:d136140931ef139a9ebfe2',
    messagingSenderId: '726043694023',
    projectId: 'shope-9bd78',
    storageBucket: 'shope-9bd78.firebasestorage.app',
    iosBundleId: 'com.example.shope',
  );
}
